export const DRIVER_TOOL_DEFINITIONS = Object.freeze([
  {
    "name": "get_module_profile",
    "description": "Get the module profile generated by analyze_module. If no valid profile exists, the server builds one automatically. Use this before build_driver_evidence_pack when an AI agent needs module-level understanding.",
    "inputSchema": {
      "type": "object",
      "properties": {
        "filename": {
          "type": "string",
          "description": "PDF filename, for example: WDT.pdf, GPT.pdf, or r01uh1069ej0115-rzg3e-DMA.pdf"
        },
        "module_type": {
          "type": "string",
          "description": "Optional module/subsystem hint used if the profile must be rebuilt."
        },
        "focus": {
          "type": "string",
          "description": "Optional focus used if the profile must be rebuilt."
        },
        "refresh": {
          "type": "boolean",
          "description": "If true, rebuild the profile before returning it."
        }
      },
      "required": [
        "filename"
      ],
      "additionalProperties": false
    }
  },
  {
    "name": "build_driver_evidence_pack",
    "description": "Build a driver-oriented evidence pack from the hardware manual. It combines module identity, likely Linux subsystem, register groups, key registers, bit-field candidates, operation sequence candidates, cautions/restrictions, and follow-up MCP calls for AI agents working in an external source workspace.",
    "inputSchema": {
      "type": "object",
      "properties": {
        "filename": {
          "type": "string",
          "description": "PDF filename, for example: WDT.pdf, GPT.pdf, or r01uh1069ej0115-rzg3e-DMA.pdf"
        },
        "module_type": {
          "type": "string",
          "description": "Optional module/subsystem hint, for example dmaengine, watchdog, pwm, timer, gpio, i2c, spi, uart, ethernet, usb, can, pcie, adc, rtc. If omitted, the server infers it from filename/registers/sections."
        },
        "focus": {
          "type": "string",
          "description": "Optional driver focus, for example minimal driver, interrupt handling, start/stop, reset, status clear, runtime PM, or debugging existing driver."
        },
        "mode": {
          "type": "string",
          "enum": [
            "adaptive",
            "fast",
            "full"
          ],
          "description": "Build mode. adaptive is the default: fast-first, budget-aware, returns partial results instead of timing out. fast uses persistent indexes only. full enables deeper dynamic searches but can be slow."
        },
        "budget_ms": {
          "type": "number",
          "description": "Internal time budget in milliseconds for this tool. Default 25000, min 5000, max 120000. The server returns partial results before this budget is exhausted."
        },
        "top_registers": {
          "type": "number",
          "description": "Maximum number of registers to include in the register map summary. Default 24, max 80."
        },
        "top_summaries": {
          "type": "number",
          "description": "Maximum number of key register summaries to include. Default 8, max 24."
        },
        "include_visual_evidence": {
          "type": "boolean",
          "description": "Include persisted visual evidence relevant to the driver focus if available. Default true."
        },
        "visual_filter": {
          "type": "string",
          "description": "Optional filter for visual evidence entries, for example clock reset pinmux interrupt timing."
        },
        "visual_status": {
          "type": "string",
          "enum": [
            "all",
            "verified",
            "unverified",
            "needs_verification",
            "observed",
            "rejected"
          ],
          "description": "Filter visual evidence by verification status. Use verified to include only verified entries. Default all."
        },
        "visual_gate": {
          "type": "string",
          "enum": [
            "advisory",
            "verified_only",
            "block_unverified"
          ],
          "description": "Driver-review gate for visual evidence. advisory warns only; verified_only includes verified entries and reports unverified matches as blockers; block_unverified keeps all entries but treats unverified matches as blockers. Default advisory."
        },
        "visual_top_k": {
          "type": "number",
          "description": "Maximum visual evidence entries to include. Default 8, max 30."
        }
      },
      "required": [
        "filename"
      ],
      "additionalProperties": false
    }
  },
  {
    "name": "source_review_prompt_pack",
    "description": "Generate a structured prompt/workflow pack for a VS Code AI agent that must review or implement a Linux driver using source code in the workspace and manual evidence from this MCP server. This avoids long ad-hoc prompts: it tells the agent which source facts to extract, which MCP tools to call, and how to produce implemented/missing/unclear conclusions.",
    "inputSchema": {
      "type": "object",
      "properties": {
        "filename": {
          "type": "string",
          "description": "PDF filename, for example GBETH.pdf, WDT.pdf, GPT.pdf, or r01uh1069ej0115-rzg3e-DMA.pdf."
        },
        "subsystem": {
          "type": "string",
          "description": "Optional Linux subsystem/profile hint, for example ethernet, dmaengine, watchdog, pwm, gpio, i2c, spi, uart, usb, can, pcie, adc, rtc."
        },
        "driver_family": {
          "type": "string",
          "description": "Optional driver family hint, for example stmmac, ravb, gpt, rzg2l-gpt, dwmac, custom."
        },
        "profile": {
          "type": "string",
          "description": "Optional explicit driver profile name, for example ethernet-stmmac."
        },
        "task": {
          "type": "string",
          "description": "Driver task/review goal, for example evaluate driver completeness, debug IRQ handling, implement reset path, or add suspend/resume."
        },
        "source_files": {
          "type": "array",
          "items": {
            "type": "string"
          },
          "description": "Optional source files that the VS Code AI agent should inspect first. MCP does not read these files."
        },
        "review_depth": {
          "type": "string",
          "enum": [
            "quick",
            "standard",
            "deep"
          ],
          "description": "Prompt strictness/depth. quick uses a short workflow; standard is default; deep requires exhaustive register-operation extraction."
        },
        "output_format": {
          "type": "string",
          "enum": [
            "report",
            "checklist",
            "patch_plan",
            "debug_plan"
          ],
          "description": "Expected final answer style for the VS Code agent. Default report."
        },
        "create_default": {
          "type": "boolean",
          "description": "Create default driver_profiles/*.json if missing. Default true."
        },
        "include_visual_evidence": {
          "type": "boolean",
          "description": "Include persisted visual evidence and visual-review workflow reminders in the generated prompt. Default true."
        },
        "visual_filter": {
          "type": "string",
          "description": "Optional filter for visual evidence entries relevant to the prompt task."
        },
        "visual_status": {
          "type": "string",
          "enum": [
            "all",
            "verified",
            "unverified",
            "needs_verification",
            "observed",
            "rejected"
          ],
          "description": "Filter persisted visual evidence by verification status. Default all."
        },
        "visual_gate": {
          "type": "string",
          "enum": [
            "advisory",
            "verified_only",
            "block_unverified"
          ],
          "description": "If verified_only or block_unverified, the generated prompt treats matching unverified visual evidence as blockers. Default advisory."
        }
      },
      "required": [
        "filename"
      ],
      "additionalProperties": false
    }
  },
  {
    "name": "compare_driver_requirements",
    "description": "Compare source-code features observed by the VS Code AI agent against the data-driven driver completeness checklist/profile. The MCP server does not read source code; pass implemented_features/source_observations/register_operations extracted by the agent. Returns implemented/missing/unclear matrix, manual verification gaps, and suggested verify_register_usage calls.",
    "inputSchema": {
      "type": "object",
      "properties": {
        "filename": {
          "type": "string",
          "description": "PDF filename, for example GBETH.pdf, WDT.pdf, GPT.pdf, or r01uh1069ej0115-rzg3e-DMA.pdf."
        },
        "subsystem": {
          "type": "string",
          "description": "Optional Linux subsystem/profile hint, for example ethernet, dmaengine, watchdog, pwm, gpio, i2c, spi, uart, usb, can, pcie, adc, rtc."
        },
        "driver_family": {
          "type": "string",
          "description": "Optional driver family hint, for example stmmac, ravb, gpt, rzg2l-gpt, dwmac, custom."
        },
        "profile": {
          "type": "string",
          "description": "Optional explicit driver profile name, for example ethernet-stmmac."
        },
        "task": {
          "type": "string",
          "description": "Optional review task/focus, for example Linux MAC driver completeness review, IRQ handling, suspend/resume, reset path, or upstream readiness."
        },
        "source_files": {
          "type": "array",
          "items": {
            "type": "string"
          },
          "description": "Source files inspected by the VS Code AI agent."
        },
        "source_summary": {
          "type": "string",
          "description": "Optional concise source-code summary produced by the AI agent after reading the workspace."
        },
        "implemented_features": {
          "type": "array",
          "items": {
            "type": "string"
          },
          "description": "Feature/checklist items observed in source code, for example clocks enabled, reset deasserted, request IRQ, parse phy-mode, register stmmac platform data."
        },
        "missing_features": {
          "type": "array",
          "items": {
            "type": "string"
          },
          "description": "Feature/checklist items explicitly observed as missing or unsupported in source code."
        },
        "source_observations": {
          "type": "array",
          "items": {
            "type": "string"
          },
          "description": "Additional source-code observations, uncertainties, TODOs, or notable implementation details extracted by the agent."
        },
        "register_operations": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "register": {
                "type": "string"
              },
              "operation": {
                "type": "string"
              },
              "bitfields": {
                "type": "array",
                "items": {
                  "type": "string"
                }
              },
              "access_type": {
                "type": "string"
              },
              "intent": {
                "type": "string"
              },
              "source_snippet": {
                "type": "string"
              }
            },
            "additionalProperties": true
          },
          "description": "Optional register operations observed in source. These are not verified automatically; output will suggest verify_register_usage calls."
        },
        "create_default": {
          "type": "boolean",
          "description": "Create default driver_profiles/*.json if missing. Default true."
        },
        "include_visual_evidence": {
          "type": "boolean",
          "description": "Include persisted visual evidence when comparing source coverage. Default true."
        },
        "visual_filter": {
          "type": "string",
          "description": "Optional filter for visual evidence entries relevant to the source review task."
        },
        "visual_status": {
          "type": "string",
          "enum": [
            "all",
            "verified",
            "unverified",
            "needs_verification",
            "observed",
            "rejected"
          ],
          "description": "Filter persisted visual evidence by verification status. Default all."
        },
        "visual_gate": {
          "type": "string",
          "enum": [
            "advisory",
            "verified_only",
            "block_unverified"
          ],
          "description": "If verified_only or block_unverified, matching unverified visual evidence becomes needsVerification/blocker. Default advisory."
        }
      },
      "required": [
        "filename"
      ],
      "additionalProperties": false
    }
  },
  {
    "name": "verify_register_usage",
    "description": "Verify a source-code register operation against the hardware manual. The AI agent should call this after reading source code in VS Code and identifying a writel/readl/regmap operation. This tool checks register existence, bit-field evidence, sequence/order hints, caution/restriction rules, reserved-bit/clear semantics risks, and returns an evidence/inference/needsVerification contract.",
    "inputSchema": {
      "type": "object",
      "properties": {
        "filename": {
          "type": "string",
          "description": "PDF filename, for example GBETH.pdf, WDT.pdf, GPT.pdf, or r01uh1069ej0115-rzg3e-DMA.pdf."
        },
        "register": {
          "type": "string",
          "description": "Register name or source-code register macro, for example DMACm_CHCTRL_n, WDTCR, GBETH_MACCR, MACCR."
        },
        "operation": {
          "type": "string",
          "description": "Source-code operation or driver intent, for example writel(SETEN), read-modify-write enable TX/RX, clear interrupt status, poll reset done."
        },
        "bitfields": {
          "type": "array",
          "items": {
            "type": "string"
          },
          "description": "Optional bit-field names/macro symbols seen in source code, for example SETEN, TE, RE, TC, ER."
        },
        "access_type": {
          "type": "string",
          "enum": [
            "auto",
            "read",
            "write",
            "raw_write",
            "read_modify_write",
            "set_bits",
            "clear_bits",
            "write_one_to_clear",
            "write_zero_to_clear",
            "poll",
            "reset"
          ],
          "description": "Optional source-code access pattern. Use raw_write for writel(value, reg), read_modify_write for readl/modify/writel, poll for read-poll loops."
        },
        "intent": {
          "type": "string",
          "enum": [
            "auto",
            "init",
            "start",
            "stop",
            "clear",
            "irq",
            "reset",
            "error",
            "status",
            "configure",
            "read",
            "write"
          ],
          "description": "Optional hardware intent. auto derives from operation/access_type."
        },
        "source_snippet": {
          "type": "string",
          "description": "Optional short source-code snippet or code summary. The MCP server does not read the repo; the AI agent may pass the relevant snippet here."
        },
        "top_k": {
          "type": "number",
          "description": "Maximum candidates for internal verification searches. Default 8."
        },
        "include_hybrid": {
          "type": "boolean",
          "description": "If true, include slower hybrid fallback search evidence. Default false when persistent indexes are available."
        },
        "budget_ms": {
          "type": "number",
          "description": "Internal time budget in milliseconds. Default 25000. Expensive fallback phases are skipped when budget is low."
        }
      },
      "required": [
        "filename",
        "register",
        "operation"
      ],
      "additionalProperties": false
    }
  },
  {
    "name": "analyze_module",
    "description": "Analyze a hardware manual at module level and create a persistent module profile. The profile summarizes likely module type, Linux subsystem, manual structure, register groups, driver-relevant topics, risk areas, and suggested MCP follow-up calls.",
    "inputSchema": {
      "type": "object",
      "properties": {
        "filename": {
          "type": "string",
          "description": "PDF filename, for example: WDT.pdf, GPT.pdf, or r01uh1069ej0115-rzg3e-DMA.pdf"
        },
        "module_type": {
          "type": "string",
          "description": "Optional module/subsystem hint, for example dmaengine, watchdog, pwm, timer, gpio, i2c, spi, uart, ethernet, usb, can, pcie, adc, rtc. If omitted, the server infers it from filename/registers/sections."
        },
        "focus": {
          "type": "string",
          "description": "Optional analysis focus, for example minimal driver, interrupt handling, start/stop, status clear, reset, runtime PM, or debugging existing driver."
        },
        "force": {
          "type": "boolean",
          "description": "Force rebuilding the module profile even if a valid profile already exists."
        }
      },
      "required": [
        "filename"
      ],
      "additionalProperties": false
    }
  },
  {
    "name": "list_driver_profiles",
    "description": "List data-driven driver review profiles from driver_profiles/. Profiles are external JSON files, so new driver/subsystem checklist knowledge can be added without changing MCP code.",
    "inputSchema": {
      "type": "object",
      "properties": {
        "create_default": {
          "type": "boolean",
          "description": "Create default profile JSON files if missing. Default true."
        }
      },
      "additionalProperties": false
    }
  },
  {
    "name": "driver_completeness_checklist",
    "description": "Build a data-driven Linux driver completeness checklist using external driver_profiles/*.json plus hardware-manual orientation. Use this for review tasks such as Ethernet/stmmac, dmaengine, watchdog, PWM, or an unknown/custom driver. It does not read source code; the VS Code agent should use the checklist to inspect source and then call verify_register_usage for each hardware operation.",
    "inputSchema": {
      "type": "object",
      "properties": {
        "filename": {
          "type": "string",
          "description": "PDF filename, for example GBETH.pdf, WDT.pdf, GPT.pdf, or r01uh1069ej0115-rzg3e-DMA.pdf."
        },
        "subsystem": {
          "type": "string",
          "description": "Optional Linux subsystem/profile hint, for example ethernet, dmaengine, watchdog, pwm, gpio, i2c, spi, uart, usb, can, pcie, adc, rtc."
        },
        "driver_family": {
          "type": "string",
          "description": "Optional driver family hint, for example stmmac, ravb, gpt, rzg2l-gpt, dwmac, custom."
        },
        "profile": {
          "type": "string",
          "description": "Optional explicit profile name, for example ethernet-stmmac. If omitted, MCP tries subsystem-driver_family, subsystem, then generic."
        },
        "task": {
          "type": "string",
          "description": "Optional review task/focus, for example Linux MAC driver completeness review, IRQ handling, suspend/resume, reset path, or upstream readiness."
        },
        "create_default": {
          "type": "boolean",
          "description": "Create default driver_profiles/*.json if missing. Default true."
        },
        "include_visual_evidence": {
          "type": "boolean",
          "description": "Include persisted visual evidence summary from indexes/<filename>.visual-evidence.json if available. Default true."
        },
        "visual_filter": {
          "type": "string",
          "description": "Optional filter for visual evidence entries, for example clock reset pinmux interrupt timing."
        },
        "visual_status": {
          "type": "string",
          "enum": [
            "all",
            "verified",
            "unverified",
            "needs_verification",
            "observed",
            "rejected"
          ],
          "description": "Filter visual evidence by verification status. Use verified to include only verified entries. Default all."
        },
        "visual_gate": {
          "type": "string",
          "enum": [
            "advisory",
            "verified_only",
            "block_unverified"
          ],
          "description": "Driver-review gate for visual evidence. advisory warns only; verified_only includes verified entries and reports unverified matches as blockers; block_unverified keeps all entries but treats unverified matches as blockers. Default advisory."
        }
      },
      "required": [
        "filename"
      ],
      "additionalProperties": false
    }
  },
  {
    "name": "prepare_driver_task",
    "description": "Prepare a driver debugging/implementation workflow for an AI agent working in an external VS Code source workspace. This tool does not read source code; it returns mandatory manual-evidence MCP calls, register/bitfield/sequence/caution checks, and source-code review checkpoints for a specific task.",
    "inputSchema": {
      "type": "object",
      "properties": {
        "filename": {
          "type": "string",
          "description": "PDF filename, for example: WDT.pdf, GPT.pdf, or r01uh1069ej0115-rzg3e-DMA.pdf"
        },
        "task": {
          "type": "string",
          "description": "Driver task or bug description, for example: debug DMA transfer does not start, add interrupt handling, implement suspend/resume, support watchdog restart, or add PWM capture."
        },
        "module_type": {
          "type": "string",
          "description": "Optional module/subsystem hint, for example dmaengine, watchdog, pwm, timer, gpio, i2c, spi, uart, ethernet, usb, can, pcie, adc, rtc."
        },
        "focus_registers": {
          "type": "array",
          "items": {
            "type": "string"
          },
          "description": "Optional register names already seen in source code or suspected by the user, for example DMACm_CHCTRL_n, DMACm_CHSTAT_n, WDTCR, WDTRR, GTCR."
        },
        "focus_bitfields": {
          "type": "array",
          "items": {
            "type": "string"
          },
          "description": "Optional bit-field names already seen in source code or suspected by the user, for example SETEN, CLREN, TC, ER, CKS, TOPS."
        },
        "top_registers": {
          "type": "number",
          "description": "Maximum number of task-related registers to include. Default 12, max 40."
        },
        "mode": {
          "type": "string",
          "enum": [
            "fast",
            "adaptive",
            "full"
          ],
          "description": "Task-plan evidence collection mode. fast/adaptive use persistent indexes and avoid dynamic full-manual fallback. Default adaptive."
        },
        "budget_ms": {
          "type": "number",
          "description": "Internal time budget in milliseconds. Default 25000. The server returns partial plans instead of timing out."
        }
      },
      "required": [
        "filename",
        "task"
      ],
      "additionalProperties": false
    }
  }
]);
